using HRM.Domain.Performance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace HRM.Infrastructure.Persistence.Configurations;

/// <summary>
/// EF Core configuration for <see cref="Recommendation"/> (US-PRF-010). Maps to the "recommendation" table
/// (singular snake_case). Tenant isolation is via the global query filter in AppDbContext + TenantInterceptor.
/// Optimistic concurrency rides the Npgsql xmin row-version convention. The compensation columns are stored as
/// plain numeric (NFR-3 encryption seam — see the Recommendation xmldoc). FKs to Employee / AppraisalCycle /
/// ManagerReview are stored as UUID columns without hard FK constraints, mirroring the codebase cross-module
/// reference pattern (tenant-scoped existence validated in the service).
/// </summary>
public sealed class RecommendationConfiguration : IEntityTypeConfiguration<Recommendation>
{
    public void Configure(EntityTypeBuilder<Recommendation> builder)
    {
        builder.ToTable("recommendation");

        builder.HasKey(r => r.Id);
        builder.Property(r => r.Id).HasColumnName("id");

        builder.Property(r => r.EmployeeId).IsRequired();
        builder.Property(r => r.CycleId).IsRequired();
        builder.Property(r => r.ManagerReviewId);
        builder.Property(r => r.BudgetId);

        builder.Property(r => r.Type)
            .HasConversion<string>()
            .HasMaxLength(30)
            .IsRequired();

        builder.Property(r => r.Status)
            .HasConversion<string>()
            .HasMaxLength(20)
            .IsRequired();

        builder.Property(r => r.IsAutoGenerated).HasDefaultValue(false).IsRequired();

        builder.Property(r => r.CurrentGrade).HasMaxLength(100);
        builder.Property(r => r.TargetGrade).HasMaxLength(100);
        builder.Property(r => r.CurrentTitle).HasMaxLength(200);
        builder.Property(r => r.TargetTitle).HasMaxLength(200);
        builder.Property(r => r.EffectiveDate);

        // SENSITIVE (NFR-3 encryption seam — stored plain numeric today; see Recommendation xmldoc).
        builder.Property(r => r.CurrentCompensation).HasPrecision(18, 2);
        builder.Property(r => r.BonusAmount).HasPrecision(18, 2);
        builder.Property(r => r.BonusPercent).HasPrecision(9, 4);
        builder.Property(r => r.IncrementAmount).HasPrecision(18, 2);
        builder.Property(r => r.IncrementPercent).HasPrecision(9, 4);

        builder.Property(r => r.TrainingCourse).HasMaxLength(300);
        builder.Property(r => r.CustomTypeLabel).HasMaxLength(100);
        builder.Property(r => r.Justification).HasMaxLength(4000);
        builder.Property(r => r.AutoGenerationRationale).HasMaxLength(500);

        builder.Property(r => r.SubmittedAt);
        builder.Property(r => r.DecidedAt);

        builder.Property(r => r.IsDeleted).HasDefaultValue(false).IsRequired();

        // Optimistic concurrency: maps to the PostgreSQL xmin system column (no schema DDL).
        builder.Property(r => r.Version).IsRowVersion();

        // FR-7/BR-7: at most one recommendation per employee per cycle (history is retained across cycles, so the
        // uniqueness is scoped to the cycle, not globally). Excludes soft-deleted rows.
        builder.HasIndex(r => new { r.TenantId, r.CycleId, r.EmployeeId })
            .IsUnique()
            .HasFilter("is_deleted = false");

        builder.HasMany(r => r.Approvers)
            .WithOne(a => a.Recommendation!)
            .HasForeignKey(a => a.RecommendationId)
            .OnDelete(DeleteBehavior.Cascade);

        builder.HasMany(r => r.Events)
            .WithOne(e => e.Recommendation!)
            .HasForeignKey(e => e.RecommendationId)
            .OnDelete(DeleteBehavior.Cascade);

        builder.HasOne(r => r.Budget)
            .WithMany()
            .HasForeignKey(r => r.BudgetId)
            .OnDelete(DeleteBehavior.SetNull);
    }
}
