using System.Globalization;
using ClosedXML.Excel;
using CsvHelper;
using HRM.Application.Common.Helpers;
using HRM.Domain.Entities;
using HRM.Application.Features.Reports.DTOs;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace HRM.Infrastructure.Services;

/// <summary>
/// Renders a generic <see cref="HrReportResult"/> into CSV / Excel (ClosedXML) / PDF (QuestPDF) bytes
/// (US-RPT-004 FR-2/FR-3/FR-4, AC-2/AC-3/AC-4). A PURE function — no DB, no tenant context, no filesystem —
/// so it returns a <c>byte[]</c> and is fully unit-testable.
///
/// <para>REUSE: the CSV (CsvHelper, UTF-8 BOM), Excel (ClosedXML, bold headers + auto-width) and PDF
/// (QuestPDF, A4 landscape table + header/footer + page numbers) paths mirror the US-PAY-009
/// <see cref="PayrollReportRenderer"/> verbatim. The ONLY additions over the payroll renderer are the
/// generic-envelope shape (object-cell rows, metadata title + applied-filters) and:
///   - BR-6: Excel includes a "Filters Applied" section in the header.
///   - AC-2/AC-3: the title + generation timestamp appear in the Excel/PDF header.
///   - BR-5: the PDF footer reads "Generated by {TenantName} via HRM SaaS" + timestamp + page numbers.</para>
///
/// <para>DEFERRED (FR-4/AC-3 chart-image part): charts are NOT embedded as PNG images. There is no
/// server-side chart-rendering infrastructure (SkiaSharp/headless-browser) in this codebase, so the PDF
/// renders branding + title + applied filters + the data table + pagination + footer only. The chart DATA
/// is still available to the FE viewer via the live report endpoint; only the static chart IMAGE in the
/// export is deferred.</para>
///
/// <para>BR-2 sensitive-masking is N/A here: the generic HR / leave / attendance reports carry no
/// bank-account / national-id PII (that is the payroll surface, handled by US-PAY-009). No masking needed.</para>
/// </summary>
public static class HrReportRenderer
{
    public static (byte[] Content, string FileName, string ContentType) Render(
        HrReportExportFormat format, HrReportResult report, string? tenantName = null)
    {
        var generatedAt = report.Metadata.GeneratedAt == default ? DateTime.UtcNow : report.Metadata.GeneratedAt;
        string baseName = $"hr-report-{Slug(report.Metadata.Type)}-{generatedAt:yyyyMMdd-HHmmss}";

        return format switch
        {
            HrReportExportFormat.Xlsx => (
                RenderXlsx(report),
                $"{baseName}.xlsx",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
            HrReportExportFormat.Pdf => (
                RenderPdf(report, tenantName),
                $"{baseName}.pdf",
                "application/pdf"),
            _ => (
                RenderCsv(report),
                $"{baseName}.csv",
                "text/csv"),
        };
    }

    // ── CSV (CsvHelper, UTF-8 BOM — same approach as PayrollReportRenderer) ───
    // FR-2/AC-4: UTF-8 BOM, comma separator, header row first, RFC-4180 escaping (CsvHelper handles quoting).
    public static byte[] RenderCsv(HrReportResult report)
    {
        using var stream = new MemoryStream();

        // Write the UTF-8 BOM explicitly (FR-2/AC-4). The StreamWriter below is created with a NO-BOM encoding
        // so we control the single leading BOM ourselves (ISSUE-198: shared with payroll + leave writers).
        CsvExport.WriteBom(stream);

        using (var writer = new StreamWriter(stream, CsvExport.NoBomEncoding, leaveOpen: true))
        using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
        {
            foreach (var header in report.Table.Columns)
                csv.WriteField(header);
            csv.NextRecord();

            foreach (var row in report.Table.Rows)
            {
                foreach (var cell in row)
                    csv.WriteField(CellText(cell));
                csv.NextRecord();
            }
        }
        return stream.ToArray();
    }

    // ── Excel (ClosedXML — same approach as PayrollReportRenderer + BR-6 filters) ──
    public static byte[] RenderXlsx(HrReportResult report)
    {
        using var workbook = new XLWorkbook();
        var sheetName = report.Metadata.Title;
        if (string.IsNullOrWhiteSpace(sheetName)) sheetName = "Report";
        if (sheetName.Length > 31) sheetName = sheetName[..31]; // Excel sheet-name limit
        var ws = workbook.Worksheets.Add(sheetName);

        int r = 1;

        // AC-2 header: report title + generation timestamp.
        ws.Cell(r, 1).Value = report.Metadata.Title;
        ws.Cell(r, 1).Style.Font.Bold = true;
        ws.Cell(r, 1).Style.Font.FontSize = 14;
        r++;
        ws.Cell(r, 1).Value = $"Generated {FmtTimestamp(report.Metadata.GeneratedAt)}";
        ws.Cell(r, 1).Style.Font.Italic = true;
        r += 2;

        // BR-6: "Filters Applied" section.
        ws.Cell(r, 1).Value = "Filters Applied";
        ws.Cell(r, 1).Style.Font.Bold = true;
        r++;
        foreach (var (label, value) in DescribeFilters(report.Metadata.AppliedFilters))
        {
            ws.Cell(r, 1).Value = label;
            ws.Cell(r, 1).Style.Font.Bold = true;
            ws.Cell(r, 2).Value = value;
            r++;
        }
        r++; // blank spacer row before the table.

        // Table header row (bold).
        for (int c = 0; c < report.Table.Columns.Count; c++)
        {
            var cell = ws.Cell(r, c + 1);
            cell.Value = report.Table.Columns[c];
            cell.Style.Font.Bold = true;
        }
        r++;

        // Data rows — cells keep their natural type where possible (numbers as numbers).
        foreach (var row in report.Table.Rows)
        {
            for (int c = 0; c < row.Length; c++)
                SetCell(ws.Cell(r, c + 1), row[c]);
            r++;
        }

        ws.Columns().AdjustToContents();

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    // ── PDF (QuestPDF — same Community license + A4 landscape setup as PayrollReportRenderer) ──
    public static byte[] RenderPdf(HrReportResult report, string? tenantName)
    {
        QuestPDF.Settings.License = LicenseType.Community;
        var accent = Colors.Blue.Darken2;
        var name = string.IsNullOrWhiteSpace(tenantName) ? "this organization" : tenantName!;
        var columns = report.Table.Columns;

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4.Landscape());
                page.Margin(28);
                page.DefaultTextStyle(t => t.FontSize(9));

                // AC-3 header: report title + generation timestamp + the applied filters.
                page.Header().BorderBottom(2).BorderColor(accent).PaddingBottom(6).Column(h =>
                {
                    h.Item().Text(report.Metadata.Title).FontSize(15).Bold().FontColor(accent);
                    h.Item().Text($"Generated {FmtTimestamp(report.Metadata.GeneratedAt)}").FontSize(8).Light();
                    foreach (var (label, value) in DescribeFilters(report.Metadata.AppliedFilters))
                        h.Item().Text($"{label}: {value}").FontSize(8).Light();
                });

                page.Content().PaddingVertical(10).Column(content =>
                {
                    if (columns.Count == 0)
                    {
                        content.Item().Text("No data for the selected filters.").Italic();
                        return;
                    }

                    content.Item().Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            for (int i = 0; i < columns.Count; i++)
                                cols.RelativeColumn();
                        });

                        table.Header(header =>
                        {
                            foreach (var col in columns)
                                header.Cell().Element(HeaderCell).Text(col).SemiBold();
                        });

                        foreach (var row in report.Table.Rows)
                            foreach (var cell in PadCells(row, columns.Count))
                                table.Cell().Element(BodyCell).Text(cell);
                    });
                });

                // BR-5: "Generated by {TenantName} via HRM SaaS" footer + timestamp + page numbers.
                page.Footer().Row(footer =>
                {
                    footer.RelativeItem().Text($"Generated by {name} via HRM SaaS — {FmtTimestamp(report.Metadata.GeneratedAt)}")
                        .FontSize(8).Light();
                    footer.ConstantItem(80).AlignRight().Text(t =>
                    {
                        t.CurrentPageNumber();
                        t.Span(" / ");
                        t.TotalPages();
                    });
                });
            });
        });

        return document.GeneratePdf();

        static IContainer HeaderCell(IContainer c) =>
            c.Background(Colors.Grey.Lighten3).Border(0.5f).BorderColor(Colors.Grey.Lighten1).PaddingVertical(3).PaddingHorizontal(4);
        static IContainer BodyCell(IContainer c) =>
            c.Border(0.5f).BorderColor(Colors.Grey.Lighten2).PaddingVertical(2).PaddingHorizontal(4);
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    /// <summary>BR-6/AC-2/AC-3: turns the resolved applied-filters block into "label: value" lines, skipping
    /// any filter that was not applied (empty collections / nulls), so the header shows only the real scope.</summary>
    private static IEnumerable<(string Label, string Value)> DescribeFilters(HrAppliedFilters f)
    {
        if (!string.IsNullOrWhiteSpace(f.DateFrom) || !string.IsNullOrWhiteSpace(f.DateTo))
            yield return ("Date Range", $"{f.DateFrom ?? "-"} to {f.DateTo ?? "-"}");
        if (f.DepartmentIds.Count > 0)
            yield return ("Departments", string.Join(", ", f.DepartmentIds));
        if (f.LocationIds.Count > 0)
            yield return ("Locations", string.Join(", ", f.LocationIds));
        if (f.EmploymentTypes.Count > 0)
            yield return ("Employment Types", string.Join(", ", f.EmploymentTypes));
        if (f.EmployeeStatuses.Count > 0)
            yield return ("Statuses", string.Join(", ", f.EmployeeStatuses));
        if (f.EmployeeId is { } empId)
            yield return ("Employee", empId.ToString());
        if (f.LeaveTypeIds.Count > 0)
            yield return ("Leave Types", string.Join(", ", f.LeaveTypeIds));
        if (f.ShiftIds.Count > 0)
            yield return ("Shifts", string.Join(", ", f.ShiftIds));
    }

    private static IEnumerable<string> PadCells(object?[] cells, int width)
    {
        for (int i = 0; i < width; i++)
            yield return i < cells.Length ? CellText(cells[i]) : string.Empty;
    }

    /// <summary>Formats a cell value to its string form (invariant culture for numbers; ISO for dates).</summary>
    private static string CellText(object? cell) => cell switch
    {
        null => string.Empty,
        string s => s,
        DateTime dt => dt.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
        IFormattable f => f.ToString(null, CultureInfo.InvariantCulture),
        _ => cell.ToString() ?? string.Empty,
    };

    /// <summary>Writes a cell into Excel keeping the natural numeric/date type where possible.</summary>
    private static void SetCell(IXLCell cell, object? value)
    {
        switch (value)
        {
            case null:
                cell.Value = string.Empty;
                break;
            case int i:
                cell.Value = i;
                break;
            case long l:
                cell.Value = l;
                break;
            case decimal d:
                cell.Value = d;
                break;
            case double db:
                cell.Value = db;
                break;
            case bool b:
                cell.Value = b;
                break;
            case DateTime dt:
                cell.Value = dt;
                break;
            default:
                cell.Value = CellText(value);
                break;
        }
    }

    private static string FmtTimestamp(DateTime ts)
    {
        var t = ts == default ? DateTime.UtcNow : ts;
        return $"{t:dd MMM yyyy HH:mm} UTC";
    }

    private static string Slug(string value)
    {
        if (string.IsNullOrWhiteSpace(value)) return "report";
        var chars = value.Trim().ToLowerInvariant()
            .Select(c => char.IsLetterOrDigit(c) ? c : '-')
            .ToArray();
        return new string(chars).Trim('-');
    }
}
