using HRM.Domain.Entities;
using HRM.Domain.Enums;

namespace HRM.Domain.Performance;

/// <summary>
/// A performance-based recommendation for one employee in one appraisal cycle (US-PRF-010): promotion, bonus,
/// increment, training nomination, lateral move, PIP referral or a custom type (FR-1). Created manually by HR or
/// as an auto-generated SUGGESTION from the rating-threshold rules (AC-2/FR-2/BR-3 — suggestions land in Draft and
/// must be reviewed + submitted). On submit (AC-3) it links to the employee's performance record (the cycle's
/// <c>ManagerReview</c>) and routes through the approval workflow (FR-4) modelled as an ordered
/// <see cref="RecommendationApprover"/> chain — the same approver-chain + status approach used by the leave
/// (US-LV-005) and attendance (US-ATT-004) approval flows. The immutable action log lives in the append-only
/// <see cref="RecommendationEvent"/> rows (FR-4/FR-7). On final approval a clearly-marked downstream-integration
/// event is raised (BR-6) for Core HR / Payroll / Training to consume later — NOT wired in this story.
///
/// Recommendation history is naturally retained across cycles (FR-7/BR-7): rows are cycle-scoped and never
/// deleted, so trend analysis reads the full set.
///
/// ENCRYPTION SEAM (NFR-3): the compensation fields (<see cref="BonusAmount"/>, <see cref="IncrementAmount"/>,
/// the percentages) are sensitive financial PII. They are stored as plain numeric today — the codebase has no
/// field/PII (pgcrypto) encryption mechanism and building one is an infra concern out of scope here (same decision
/// as US-PRF-008). When a platform PII-encryption strategy lands, apply it via an EF ValueConverter with no schema
/// change. TODO(US-PLT PII-encryption).
///
/// Tenant-scoped via <see cref="BaseEntity.TenantId"/> + the EF global query filter + <c>TenantInterceptor</c>
/// (NFR-2). Maps to the "recommendation" table.
/// </summary>
public sealed class Recommendation : BaseEntity
{
    /// <summary>The employee the recommendation is for (FK to <see cref="Employee"/>, required).</summary>
    public Guid EmployeeId { get; set; }

    /// <summary>The appraisal cycle the recommendation belongs to (FK to <see cref="AppraisalCycle"/>, required).</summary>
    public Guid CycleId { get; set; }

    /// <summary>
    /// The performance record this recommendation is linked to on submit (FK to <see cref="ManagerReview"/>,
    /// AC-3). Null while Draft or when the employee has no submitted manager review.
    /// </summary>
    public Guid? ManagerReviewId { get; set; }

    /// <summary>The recommendation type (FR-1).</summary>
    public RecommendationType Type { get; set; }

    /// <summary>Lifecycle status (§7). Defaults to Draft.</summary>
    public RecommendationStatus Status { get; set; } = RecommendationStatus.Draft;

    /// <summary>True when this row was produced by the auto-generation rules (AC-2/BR-3) rather than created by hand.</summary>
    public bool IsAutoGenerated { get; set; }

    // ── Promotion / lateral-move details (BR-5) ─────────────────────────

    /// <summary>The current grade/band of the employee at recommendation time (FR-5 comparison view).</summary>
    public string? CurrentGrade { get; set; }

    /// <summary>The recommended target grade/band (BR-5 — required for a promotion).</summary>
    public string? TargetGrade { get; set; }

    /// <summary>The current job title (FR-5 comparison view).</summary>
    public string? CurrentTitle { get; set; }

    /// <summary>The recommended target job title (FR-5 comparison view, optional).</summary>
    public string? TargetTitle { get; set; }

    /// <summary>The effective date of the change (BR-5 — required for a promotion).</summary>
    public DateOnly? EffectiveDate { get; set; }

    // ── Compensation details (NFR-3 encryption seam) ────────────────────

    /// <summary>SENSITIVE (NFR-3). The current compensation figure (FR-5 comparison view, optional).</summary>
    public decimal? CurrentCompensation { get; set; }

    /// <summary>SENSITIVE (NFR-3). The bonus amount (FR-1 — for a Bonus). Charged to the budget (FR-8).</summary>
    public decimal? BonusAmount { get; set; }

    /// <summary>The bonus as a percentage of compensation (FR-1 — alternative to <see cref="BonusAmount"/>).</summary>
    public decimal? BonusPercent { get; set; }

    /// <summary>SENSITIVE (NFR-3). The increment amount (FR-1 — for an Increment). Charged to the budget (FR-8).</summary>
    public decimal? IncrementAmount { get; set; }

    /// <summary>The increment as a percentage of compensation (FR-1 — alternative to <see cref="IncrementAmount"/>).</summary>
    public decimal? IncrementPercent { get; set; }

    // ── Training / custom details ───────────────────────────────────────

    /// <summary>The training course nominated for (FR-1 — for a TrainingNomination).</summary>
    public string? TrainingCourse { get; set; }

    /// <summary>The custom-type label (FR-1 — for a Custom recommendation).</summary>
    public string? CustomTypeLabel { get; set; }

    // ── Justification / rationale ───────────────────────────────────────

    /// <summary>
    /// Free-text justification (FR-3 — MANDATORY when HR manually overrides an auto-generated suggestion). Also
    /// captures the rationale for any manual recommendation. Max 4000 chars.
    /// </summary>
    public string? Justification { get; set; }

    /// <summary>The rule rationale recorded when auto-generated, e.g. "Final score 4.6 ≥ 4.5 threshold" (AC-2/FR-2).</summary>
    public string? AutoGenerationRationale { get; set; }

    /// <summary>The budget this recommendation is charged against (FK to <see cref="RecommendationBudget"/>, FR-8). Optional.</summary>
    public Guid? BudgetId { get; set; }

    // ── Workflow timestamps ─────────────────────────────────────────────

    /// <summary>UTC timestamp the recommendation was submitted into the approval workflow (AC-3). Null while Draft.</summary>
    public DateTime? SubmittedAt { get; set; }

    /// <summary>UTC timestamp the recommendation reached a terminal Approved/Rejected state. Null otherwise.</summary>
    public DateTime? DecidedAt { get; set; }

    /// <summary>
    /// Optimistic concurrency token (prevents lost updates). Maps to the PostgreSQL xmin system column via the
    /// Npgsql row-version convention (no schema DDL); the InMemory test provider ignores it.
    /// </summary>
    public uint Version { get; set; }

    // ── Navigation ─────────────────────────────────────────────────────
    public Employee? Employee { get; set; }
    public AppraisalCycle? Cycle { get; set; }
    public RecommendationBudget? Budget { get; set; }

    /// <summary>The ordered approver chain for the approval workflow (FR-4).</summary>
    public List<RecommendationApprover> Approvers { get; set; } = [];

    /// <summary>The immutable, append-only action/audit log (FR-4/FR-7).</summary>
    public List<RecommendationEvent> Events { get; set; } = [];

    /// <summary>The single monetary amount charged to the budget (FR-8): bonus amount, else increment amount, else 0.</summary>
    public decimal BudgetCharge => BonusAmount ?? IncrementAmount ?? 0m;
}
