using HRM.Domain.Enums;
using HRM.Domain.Performance;

namespace HRM.Application.Features.Performance.DTOs;

// ════════════════════════════════════════════════════════════════════════
//  US-PRF-010 — Performance-based recommendations: DTOs + request/input records
// ════════════════════════════════════════════════════════════════════════

// ── Output DTOs ─────────────────────────────────────────────────────────

/// <summary>One approver step in a recommendation's approval chain (US-PRF-010 FR-4).</summary>
public sealed record RecommendationApproverDto
{
    public Guid Id { get; init; }
    public Guid ApproverEmployeeId { get; init; }
    public string ApproverName { get; init; } = string.Empty;
    public int StepOrder { get; init; }
    public RecommendationApproverDecision Decision { get; init; }
    public string DecisionName { get; init; } = string.Empty;
    public DateTime? DecidedAt { get; init; }
    public string? Comment { get; init; }
}

/// <summary>One immutable recommendation audit-log entry (US-PRF-010 FR-4/FR-7).</summary>
public sealed record RecommendationEventDto
{
    public Guid Id { get; init; }
    public RecommendationEventType EventType { get; init; }
    public string EventTypeName { get; init; } = string.Empty;
    public string ActorName { get; init; } = string.Empty;
    public DateTime OccurredAt { get; init; }
    public string? Detail { get; init; }
}

/// <summary>
/// A full recommendation record (US-PRF-010). Returned from generate/override/submit/approve/reject and the
/// workspace get. Includes the FR-5 current-vs-recommended comparison fields, the approval chain (FR-4) and the
/// immutable event history (FR-7). Compensation fields are sensitive (NFR-3 seam) — served to authorized HR.
/// </summary>
public sealed record RecommendationDto
{
    public Guid Id { get; init; }
    public Guid EmployeeId { get; init; }
    public string EmployeeName { get; init; } = string.Empty;
    public string EmployeeNo { get; init; } = string.Empty;
    public Guid CycleId { get; init; }
    public Guid? ManagerReviewId { get; init; }

    public RecommendationType Type { get; init; }
    public string TypeName { get; init; } = string.Empty;
    public RecommendationStatus Status { get; init; }
    public string StatusName { get; init; } = string.Empty;
    public bool IsAutoGenerated { get; init; }

    // FR-5 comparison (current vs recommended).
    public string? CurrentGrade { get; init; }
    public string? TargetGrade { get; init; }
    public string? CurrentTitle { get; init; }
    public string? TargetTitle { get; init; }
    public DateOnly? EffectiveDate { get; init; }
    public decimal? CurrentCompensation { get; init; }

    // Compensation details (NFR-3 seam).
    public decimal? BonusAmount { get; init; }
    public decimal? BonusPercent { get; init; }
    public decimal? IncrementAmount { get; init; }
    public decimal? IncrementPercent { get; init; }

    public string? TrainingCourse { get; init; }
    public string? CustomTypeLabel { get; init; }
    public string? Justification { get; init; }
    public string? AutoGenerationRationale { get; init; }

    public Guid? BudgetId { get; init; }
    public decimal BudgetCharge { get; init; }

    public DateTime? SubmittedAt { get; init; }
    public DateTime? DecidedAt { get; init; }

    // Context (the employee's appraisal outcome — AC-1 workspace row).
    public decimal? FinalScore { get; init; }
    public ReviewFlag ManagerFlag { get; init; }
    public string ManagerFlagName { get; init; } = string.Empty;

    public IReadOnlyList<RecommendationApproverDto> Approvers { get; init; } = [];
    public IReadOnlyList<RecommendationEventDto> Events { get; init; } = [];
}

/// <summary>
/// One row of the recommendation workspace (US-PRF-010 AC-1): an employee in a completed cycle with their final
/// score, current grade/band/title/compensation, tenure, manager flag (US-PRF-003), and their existing
/// recommendation (null when none yet). HR sees all rows; a manager sees only their direct reports (AC-5).
/// </summary>
public sealed record RecommendationWorkspaceRowDto
{
    public Guid EmployeeId { get; init; }
    public string EmployeeName { get; init; } = string.Empty;
    public string EmployeeNo { get; init; } = string.Empty;
    public Guid DepartmentId { get; init; }
    public string DepartmentName { get; init; } = string.Empty;
    public string? CurrentGrade { get; init; }
    public string? CurrentTitle { get; init; }
    public decimal? CurrentCompensation { get; init; }
    public int TenureMonths { get; init; }
    public decimal? FinalScore { get; init; }
    public ReviewFlag ManagerFlag { get; init; }
    public string ManagerFlagName { get; init; } = string.Empty;
    public Guid? ManagerReviewId { get; init; }

    /// <summary>The existing recommendation for this employee in the cycle, if any (AC-1/AC-5 status column).</summary>
    public RecommendationDto? Recommendation { get; init; }
}

/// <summary>The paginated recommendation workspace (US-PRF-010 AC-1, NFR-4 pagination).</summary>
public sealed record RecommendationWorkspaceDto
{
    public Guid CycleId { get; init; }
    public string CycleName { get; init; } = string.Empty;
    public int RatingScaleMax { get; init; }
    public int Page { get; init; }
    public int PageSize { get; init; }
    public int TotalCount { get; init; }
    public IReadOnlyList<RecommendationWorkspaceRowDto> Rows { get; init; } = [];
    public RecommendationBudgetDto? Budget { get; init; }
}

/// <summary>Budget tracker state (US-PRF-010 FR-8/BR-4).</summary>
public sealed record RecommendationBudgetDto
{
    public Guid Id { get; init; }
    public Guid CycleId { get; init; }
    public string Name { get; init; } = string.Empty;
    public decimal AllocatedAmount { get; init; }
    public decimal ConsumedAmount { get; init; }
    public decimal RemainingAmount { get; init; }
    public string Currency { get; init; } = "USD";
    public bool IsExceeded { get; init; }
}

/// <summary>One auto-generation rule (US-PRF-010 FR-2/BR-3).</summary>
public sealed record RecommendationRuleDto
{
    public Guid Id { get; init; }
    public string Name { get; init; } = string.Empty;
    public decimal MinFinalScore { get; init; }
    public RecommendationType RecommendedType { get; init; }
    public string RecommendedTypeName { get; init; } = string.Empty;
    public decimal? DefaultBonusPercent { get; init; }
    public decimal? DefaultIncrementPercent { get; init; }
    public bool IsActive { get; init; }
}

/// <summary>Aggregate recommendation summary stats (US-PRF-010 AC-4/FR-6).</summary>
public sealed record RecommendationSummaryDto
{
    public Guid CycleId { get; init; }
    public string CycleName { get; init; } = string.Empty;
    public int TotalRecommendations { get; init; }
    public int TotalPromotions { get; init; }
    public decimal TotalBonusPoolAllocated { get; init; }
    public decimal TotalIncrementAllocated { get; init; }
    public int TotalTrainingNominations { get; init; }
    public IReadOnlyList<RecommendationCountByStatusDto> ByStatus { get; init; } = [];
    public IReadOnlyList<RecommendationIncrementByDeptDto> IncrementByDepartment { get; init; } = [];
    public RecommendationBudgetDto? Budget { get; init; }

    /// <summary>The previous cycle's totals for comparison (AC-4). Null when there is no prior cycle.</summary>
    public RecommendationPreviousCycleDto? PreviousCycle { get; init; }
}

public sealed record RecommendationCountByStatusDto
{
    public RecommendationStatus Status { get; init; }
    public string StatusName { get; init; } = string.Empty;
    public int Count { get; init; }
}

public sealed record RecommendationIncrementByDeptDto
{
    public Guid DepartmentId { get; init; }
    public string DepartmentName { get; init; } = string.Empty;
    public int RecommendationCount { get; init; }
    public decimal TotalIncrementAmount { get; init; }
}

public sealed record RecommendationPreviousCycleDto
{
    public Guid CycleId { get; init; }
    public string CycleName { get; init; } = string.Empty;
    public int TotalPromotions { get; init; }
    public decimal TotalBonusPoolAllocated { get; init; }
    public decimal TotalIncrementAllocated { get; init; }
}

/// <summary>Result of an auto-generation run (US-PRF-010 AC-2/FR-2/BR-3).</summary>
public sealed record AutoGenerateResultDto
{
    public Guid CycleId { get; init; }
    public int EmployeesEvaluated { get; init; }
    public int SuggestionsCreated { get; init; }
    public int SuggestionsSkipped { get; init; }
    public IReadOnlyList<RecommendationDto> Suggestions { get; init; } = [];
}

/// <summary>An exported recommendation report file (US-PRF-010 FR-6, reusing the US-PRF-007 export pattern).</summary>
public sealed record RecommendationExportResult
{
    public byte[] FileContent { get; init; } = [];
    public string ContentType { get; init; } = "application/octet-stream";
    public string FileName { get; init; } = "recommendations.csv";
}

// ── Request bodies (controller) ─────────────────────────────────────────

/// <summary>The compensation/detail payload shared by create/override (US-PRF-010 FR-1/BR-5).</summary>
public sealed record RecommendationDetailsRequest(
    string? TargetGrade,
    string? TargetTitle,
    DateOnly? EffectiveDate,
    decimal? BonusAmount,
    decimal? BonusPercent,
    decimal? IncrementAmount,
    decimal? IncrementPercent,
    string? TrainingCourse,
    string? CustomTypeLabel,
    Guid? BudgetId);

/// <summary>Manually create OR override a recommendation for an employee in a cycle (US-PRF-010 FR-1/FR-3/BR-5).</summary>
public sealed record SaveRecommendationRequest(
    Guid EmployeeId,
    Guid CycleId,
    RecommendationType Type,
    RecommendationDetailsRequest Details,
    string? Justification);

/// <summary>Auto-generate recommendation suggestions across a cycle (US-PRF-010 AC-2/FR-2/BR-3).</summary>
public sealed record AutoGenerateRecommendationsRequest(Guid CycleId);

/// <summary>Submit a recommendation into the approval workflow (US-PRF-010 AC-3/FR-4).</summary>
public sealed record SubmitRecommendationRequest(IReadOnlyList<Guid>? ApproverEmployeeIds);

/// <summary>An approver's approve/reject decision (US-PRF-010 FR-4).</summary>
public sealed record DecideRecommendationRequest(string? Comment);

/// <summary>Create or update the cycle's bonus/increment budget (US-PRF-010 FR-8).</summary>
public sealed record SaveBudgetRequest(Guid CycleId, string Name, decimal AllocatedAmount, string? Currency);

/// <summary>Create or update an auto-generation rule (US-PRF-010 FR-2).</summary>
public sealed record SaveRuleRequest(
    string Name,
    decimal MinFinalScore,
    RecommendationType RecommendedType,
    decimal? DefaultBonusPercent,
    decimal? DefaultIncrementPercent,
    bool IsActive);

// ── Service-layer inputs (decouple handlers from the service) ───────────

public sealed record RecommendationDetailsInput(
    string? TargetGrade,
    string? TargetTitle,
    DateOnly? EffectiveDate,
    decimal? BonusAmount,
    decimal? BonusPercent,
    decimal? IncrementAmount,
    decimal? IncrementPercent,
    string? TrainingCourse,
    string? CustomTypeLabel,
    Guid? BudgetId);

public sealed record SaveRecommendationInput(
    Guid EmployeeId,
    Guid CycleId,
    RecommendationType Type,
    RecommendationDetailsInput Details,
    string? Justification,
    string? ClientIpAddress);

public sealed record SubmitRecommendationInput(
    Guid RecommendationId,
    IReadOnlyList<Guid> ApproverEmployeeIds,
    string? ClientIpAddress);

public sealed record DecideRecommendationInput(
    Guid RecommendationId,
    bool Approve,
    string? Comment,
    string? ClientIpAddress);

public sealed record SaveBudgetInput(
    Guid CycleId,
    string Name,
    decimal AllocatedAmount,
    string? Currency);

public sealed record SaveRuleInput(
    Guid? RuleId,
    string Name,
    decimal MinFinalScore,
    RecommendationType RecommendedType,
    decimal? DefaultBonusPercent,
    decimal? DefaultIncrementPercent,
    bool IsActive);

public sealed record RecommendationWorkspaceQueryInput(Guid? CycleId, int Page, int PageSize);
