namespace HRM.Application.Common.Interfaces;

/// <summary>
/// Storage seam for generated report-export files (US-LV-012 FR-5, §7).
///
/// Large exports (&gt; 5,000 rows) are generated by a Hangfire background job and stored at a
/// tenant-scoped path <c>{tenantId}/reports/leave/{reportId}.{ext}</c> in blob storage, then the user
/// is notified when the file is ready (AC-5). No blob-storage provider exists in this codebase yet, so
/// this seam is implemented by a local/log-only adapter that writes to a tenant-scoped temp path and
/// logs the location.
///
/// TODO(blob-storage): replace the local/log-only implementation with a real tenant-scoped blob store
///   (S3/Azure Blob/etc.) and wire a signed-download URL + a real notification dispatch. The 30-day
///   retention purge (§10) belongs there too.
/// </summary>
public interface IReportExportStorage
{
    /// <summary>
    /// Persists an export file under the tenant-scoped report path and returns an opaque locator
    /// (a path/URL) the caller can surface to the user. The reportId disambiguates concurrent exports.
    /// </summary>
    Task<string> SaveAsync(
        Guid tenantId,
        Guid reportId,
        string fileName,
        string contentType,
        byte[] content,
        CancellationToken cancellationToken = default);
}
