/**
 * US-CHR-007: Static reference data for location forms.
 *
 * Countries: ISO 3166-1 alpha-2 subset (common countries first, then full list).
 * Time zones: IANA time zone database identifiers, common zones highlighted.
 *
 * Both datasets are bundled as static constants to avoid external API calls
 * or paid libraries. The country list covers ~250 ISO 3166-1 entries.
 * The time zone list covers ~100 commonly used IANA identifiers.
 */

export interface ICountryOption {
  code: string; // ISO 3166-1 alpha-2
  name: string;
}

export interface ITimeZoneOption {
  id: string; // IANA identifier
  label: string; // Human-readable label
  utcOffset: string; // e.g. "UTC+05:30"
  isCommon: boolean;
}

/**
 * Common time zones displayed at the top of the selector.
 * Followed by a full list of IANA identifiers.
 */
export const TIME_ZONES: ITimeZoneOption[] = [
  // --- Common zones (highlighted at top) ---
  { id: 'UTC', label: 'UTC', utcOffset: 'UTC+00:00', isCommon: true },
  { id: 'America/New_York', label: 'Eastern Time (US)', utcOffset: 'UTC-05:00', isCommon: true },
  { id: 'America/Chicago', label: 'Central Time (US)', utcOffset: 'UTC-06:00', isCommon: true },
  { id: 'America/Denver', label: 'Mountain Time (US)', utcOffset: 'UTC-07:00', isCommon: true },
  { id: 'America/Los_Angeles', label: 'Pacific Time (US)', utcOffset: 'UTC-08:00', isCommon: true },
  { id: 'Europe/London', label: 'London (GMT)', utcOffset: 'UTC+00:00', isCommon: true },
  { id: 'Europe/Paris', label: 'Central European', utcOffset: 'UTC+01:00', isCommon: true },
  { id: 'Europe/Berlin', label: 'Berlin', utcOffset: 'UTC+01:00', isCommon: true },
  { id: 'Asia/Kolkata', label: 'India (IST)', utcOffset: 'UTC+05:30', isCommon: true },
  { id: 'Asia/Colombo', label: 'Sri Lanka', utcOffset: 'UTC+05:30', isCommon: true },
  { id: 'Asia/Tokyo', label: 'Japan (JST)', utcOffset: 'UTC+09:00', isCommon: true },
  { id: 'Asia/Shanghai', label: 'China (CST)', utcOffset: 'UTC+08:00', isCommon: true },
  { id: 'Asia/Singapore', label: 'Singapore', utcOffset: 'UTC+08:00', isCommon: true },
  { id: 'Asia/Dubai', label: 'Dubai (GST)', utcOffset: 'UTC+04:00', isCommon: true },
  { id: 'Australia/Sydney', label: 'Sydney (AEST)', utcOffset: 'UTC+10:00', isCommon: true },
  { id: 'Pacific/Auckland', label: 'New Zealand', utcOffset: 'UTC+12:00', isCommon: true },
  // --- Extended list ---
  { id: 'Africa/Cairo', label: 'Cairo', utcOffset: 'UTC+02:00', isCommon: false },
  { id: 'Africa/Johannesburg', label: 'Johannesburg', utcOffset: 'UTC+02:00', isCommon: false },
  { id: 'Africa/Lagos', label: 'Lagos', utcOffset: 'UTC+01:00', isCommon: false },
  { id: 'Africa/Nairobi', label: 'Nairobi', utcOffset: 'UTC+03:00', isCommon: false },
  { id: 'America/Anchorage', label: 'Alaska', utcOffset: 'UTC-09:00', isCommon: false },
  { id: 'America/Argentina/Buenos_Aires', label: 'Buenos Aires', utcOffset: 'UTC-03:00', isCommon: false },
  { id: 'America/Bogota', label: 'Bogota', utcOffset: 'UTC-05:00', isCommon: false },
  { id: 'America/Caracas', label: 'Caracas', utcOffset: 'UTC-04:00', isCommon: false },
  { id: 'America/Halifax', label: 'Atlantic Time', utcOffset: 'UTC-04:00', isCommon: false },
  { id: 'America/Lima', label: 'Lima', utcOffset: 'UTC-05:00', isCommon: false },
  { id: 'America/Mexico_City', label: 'Mexico City', utcOffset: 'UTC-06:00', isCommon: false },
  { id: 'America/Phoenix', label: 'Arizona (no DST)', utcOffset: 'UTC-07:00', isCommon: false },
  { id: 'America/Santiago', label: 'Santiago', utcOffset: 'UTC-04:00', isCommon: false },
  { id: 'America/Sao_Paulo', label: 'Sao Paulo', utcOffset: 'UTC-03:00', isCommon: false },
  { id: 'America/Toronto', label: 'Toronto', utcOffset: 'UTC-05:00', isCommon: false },
  { id: 'America/Vancouver', label: 'Vancouver', utcOffset: 'UTC-08:00', isCommon: false },
  { id: 'Asia/Almaty', label: 'Almaty', utcOffset: 'UTC+06:00', isCommon: false },
  { id: 'Asia/Baghdad', label: 'Baghdad', utcOffset: 'UTC+03:00', isCommon: false },
  { id: 'Asia/Bangkok', label: 'Bangkok', utcOffset: 'UTC+07:00', isCommon: false },
  { id: 'Asia/Dhaka', label: 'Dhaka', utcOffset: 'UTC+06:00', isCommon: false },
  { id: 'Asia/Hong_Kong', label: 'Hong Kong', utcOffset: 'UTC+08:00', isCommon: false },
  { id: 'Asia/Istanbul', label: 'Istanbul', utcOffset: 'UTC+03:00', isCommon: false },
  { id: 'Asia/Jakarta', label: 'Jakarta', utcOffset: 'UTC+07:00', isCommon: false },
  { id: 'Asia/Karachi', label: 'Karachi', utcOffset: 'UTC+05:00', isCommon: false },
  { id: 'Asia/Kuala_Lumpur', label: 'Kuala Lumpur', utcOffset: 'UTC+08:00', isCommon: false },
  { id: 'Asia/Manila', label: 'Manila', utcOffset: 'UTC+08:00', isCommon: false },
  { id: 'Asia/Riyadh', label: 'Riyadh', utcOffset: 'UTC+03:00', isCommon: false },
  { id: 'Asia/Seoul', label: 'Seoul', utcOffset: 'UTC+09:00', isCommon: false },
  { id: 'Asia/Taipei', label: 'Taipei', utcOffset: 'UTC+08:00', isCommon: false },
  { id: 'Asia/Tehran', label: 'Tehran', utcOffset: 'UTC+03:30', isCommon: false },
  { id: 'Atlantic/Reykjavik', label: 'Reykjavik', utcOffset: 'UTC+00:00', isCommon: false },
  { id: 'Australia/Melbourne', label: 'Melbourne', utcOffset: 'UTC+10:00', isCommon: false },
  { id: 'Australia/Perth', label: 'Perth', utcOffset: 'UTC+08:00', isCommon: false },
  { id: 'Europe/Amsterdam', label: 'Amsterdam', utcOffset: 'UTC+01:00', isCommon: false },
  { id: 'Europe/Athens', label: 'Athens', utcOffset: 'UTC+02:00', isCommon: false },
  { id: 'Europe/Brussels', label: 'Brussels', utcOffset: 'UTC+01:00', isCommon: false },
  { id: 'Europe/Bucharest', label: 'Bucharest', utcOffset: 'UTC+02:00', isCommon: false },
  { id: 'Europe/Dublin', label: 'Dublin', utcOffset: 'UTC+00:00', isCommon: false },
  { id: 'Europe/Helsinki', label: 'Helsinki', utcOffset: 'UTC+02:00', isCommon: false },
  { id: 'Europe/Lisbon', label: 'Lisbon', utcOffset: 'UTC+00:00', isCommon: false },
  { id: 'Europe/Madrid', label: 'Madrid', utcOffset: 'UTC+01:00', isCommon: false },
  { id: 'Europe/Moscow', label: 'Moscow', utcOffset: 'UTC+03:00', isCommon: false },
  { id: 'Europe/Oslo', label: 'Oslo', utcOffset: 'UTC+01:00', isCommon: false },
  { id: 'Europe/Prague', label: 'Prague', utcOffset: 'UTC+01:00', isCommon: false },
  { id: 'Europe/Rome', label: 'Rome', utcOffset: 'UTC+01:00', isCommon: false },
  { id: 'Europe/Stockholm', label: 'Stockholm', utcOffset: 'UTC+01:00', isCommon: false },
  { id: 'Europe/Vienna', label: 'Vienna', utcOffset: 'UTC+01:00', isCommon: false },
  { id: 'Europe/Warsaw', label: 'Warsaw', utcOffset: 'UTC+01:00', isCommon: false },
  { id: 'Europe/Zurich', label: 'Zurich', utcOffset: 'UTC+01:00', isCommon: false },
  { id: 'Pacific/Honolulu', label: 'Hawaii', utcOffset: 'UTC-10:00', isCommon: false },
  { id: 'Pacific/Fiji', label: 'Fiji', utcOffset: 'UTC+12:00', isCommon: false },
];

/**
 * ISO 3166-1 country list (name only, no flag icons to keep bundle small).
 * Sorted alphabetically. Common countries can be promoted to the top in the
 * UI by the component's filter logic.
 */
export const COUNTRIES: ICountryOption[] = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AL', name: 'Albania' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AG', name: 'Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BR', name: 'Brazil' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'CA', name: 'Canada' },
  { code: 'CV', name: 'Cape Verde' },
  { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CO', name: 'Colombia' },
  { code: 'KM', name: 'Comoros' },
  { code: 'CG', name: 'Congo' },
  { code: 'CD', name: 'Congo (DRC)' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'HR', name: 'Croatia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'DK', name: 'Denmark' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'EE', name: 'Estonia' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GR', name: 'Greece' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japan' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KP', name: 'Korea (North)' },
  { code: 'KR', name: 'Korea (South)' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: 'Laos' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libya' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MV', name: 'Maldives' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MH', name: 'Marshall Islands' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'MX', name: 'Mexico' },
  { code: 'FM', name: 'Micronesia' },
  { code: 'MD', name: 'Moldova' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'MK', name: 'North Macedonia' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PW', name: 'Palau' },
  { code: 'PS', name: 'Palestine' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russia' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'KN', name: 'Saint Kitts and Nevis' },
  { code: 'LC', name: 'Saint Lucia' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' },
  { code: 'ST', name: 'Sao Tome and Principe' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'SB', name: 'Solomon Islands' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'SS', name: 'South Sudan' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SY', name: 'Syria' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Turkey' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VA', name: 'Vatican City' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'YE', name: 'Yemen' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
];
