import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideNoopAnimations } from '@angular/platform-browser/animations';
import { of, throwError } from 'rxjs';

import { TeamRecommendationsComponent } from './team-recommendations.component';
import { RecommendationService } from '../../services/recommendation.service';
import {
  ICompletedCycleOption,
  IRecommendationRow,
} from '../../models/recommendation.models';

function row(overrides: Partial<IRecommendationRow> = {}): IRecommendationRow {
  return {
    recommendationId: 'r-1',
    employeeId: 'e-1',
    employeeName: 'Alex Doe',
    employeeNo: 'E1',
    departmentId: 'd-1',
    departmentName: 'Eng',
    jobTitle: 'Engineer',
    finalScore: 4.2,
    scoreScaleMax: 5,
    currentGrade: 'G3',
    currentCompensation: null, // manager view: no comp visibility
    tenureMonths: 18,
    managerFlag: null,
    status: 'Submitted',
    autoGenerated: true,
    detail: {
      type: 'Bonus',
      amount: null,
      percentage: null,
      targetGrade: null,
      targetTitle: null,
      effectiveDate: null,
      trainingCourse: null,
      justification: null,
    },
    ...overrides,
  };
}

const cycles: ICompletedCycleOption[] = [
  { cycleId: 'c-1', cycleName: '2026 Annual', ratingsPublishedOn: '2026-05-01' },
];

describe('TeamRecommendationsComponent (US-PRF-010 AC-5)', () => {
  let fixture: ComponentFixture<TeamRecommendationsComponent>;
  let component: TeamRecommendationsComponent;
  let serviceSpy: jasmine.SpyObj<RecommendationService>;

  async function setup(rows: IRecommendationRow[]): Promise<void> {
    serviceSpy = jasmine.createSpyObj<RecommendationService>(
      'RecommendationService',
      ['getCompletedCycles', 'getTeamRecommendations'],
    );
    serviceSpy.getCompletedCycles.and.returnValue(of(cycles));
    serviceSpy.getTeamRecommendations.and.returnValue(of(rows));

    await TestBed.configureTestingModule({
      imports: [TeamRecommendationsComponent],
      providers: [
        provideNoopAnimations(),
        { provide: RecommendationService, useValue: serviceSpy },
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(TeamRecommendationsComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  }

  it('loads the team list for the active cycle (AC-5 scope)', async () => {
    await setup([row(), row({ recommendationId: 'r-2', employeeName: 'Jo Q' })]);
    expect(serviceSpy.getTeamRecommendations).toHaveBeenCalledWith('c-1');
    expect(component.rows().length).toBe(2);
  });

  it('uses the TEAM endpoint, never the HR workspace (distinct from HR view)', async () => {
    await setup([row()]);
    // The component only knows about the direct-reports endpoint; the HR workspace
    // method is not part of its surface.
    expect(serviceSpy.getTeamRecommendations).toHaveBeenCalled();
    expect((serviceSpy as unknown as Record<string, unknown>)['getWorkspace'])
      .toBeUndefined();
  });

  it('renders one card per direct report with a status chip', async () => {
    await setup([row({ status: 'Approved' })]);
    const el = fixture.nativeElement as HTMLElement;
    expect(el.querySelectorAll('[data-testid="team-card"]').length).toBe(1);
    expect(
      el.querySelector('[data-testid="status-chip"]')?.textContent,
    ).toContain('Approved');
  });

  it('shows an empty state when the team has no recommendations', async () => {
    await setup([]);
    expect(
      (fixture.nativeElement as HTMLElement).querySelector(
        '[data-testid="empty"]',
      ),
    ).toBeTruthy();
  });

  it('shows an error state with retry on failure', async () => {
    serviceSpy = jasmine.createSpyObj<RecommendationService>(
      'RecommendationService',
      ['getCompletedCycles', 'getTeamRecommendations'],
    );
    serviceSpy.getCompletedCycles.and.returnValue(of(cycles));
    serviceSpy.getTeamRecommendations.and.returnValue(
      throwError(() => new Error('x')),
    );
    await TestBed.configureTestingModule({
      imports: [TeamRecommendationsComponent],
      providers: [
        provideNoopAnimations(),
        { provide: RecommendationService, useValue: serviceSpy },
      ],
    }).compileComponents();
    fixture = TestBed.createComponent(TeamRecommendationsComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();

    expect(component.error()).toBeTruthy();
    expect(component.loading()).toBeFalse();
  });
});
