import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { provideNoopAnimations } from '@angular/platform-browser/animations';
import { of, throwError } from 'rxjs';
import { ToastrService } from 'ngx-toastr';

import { RecommendationWorkspaceComponent } from './recommendation-workspace.component';
import { RecommendationService } from '../../services/recommendation.service';
import {
  ICompletedCycleOption,
  IRecommendationRow,
  IRecommendationWorkspace,
} from '../../models/recommendation.models';

function row(overrides: Partial<IRecommendationRow> = {}): IRecommendationRow {
  return {
    recommendationId: 'r-1',
    employeeId: 'e-1',
    employeeName: 'Alex Doe',
    employeeNo: 'E1',
    departmentId: 'd-1',
    departmentName: 'Eng',
    jobTitle: 'Engineer',
    finalScore: 4.6,
    scoreScaleMax: 5,
    currentGrade: 'G3',
    currentCompensation: 60000,
    tenureMonths: 30,
    managerFlag: null,
    status: 'Draft',
    autoGenerated: true,
    detail: {
      type: 'None',
      amount: null,
      percentage: null,
      targetGrade: null,
      targetTitle: null,
      effectiveDate: null,
      trainingCourse: null,
      justification: null,
    },
    ...overrides,
  };
}

function workspace(
  rows: IRecommendationRow[],
  budget?: Partial<IRecommendationWorkspace['budget']>,
): IRecommendationWorkspace {
  return {
    cycleId: 'c-1',
    cycleName: '2026 Annual',
    page: { rows, totalCount: rows.length, page: 1, pageSize: 20 },
    budget: {
      enabled: true,
      currency: 'USD',
      allocated: 100000,
      consumed: 50000,
      ...budget,
    },
    compensationVisible: true,
    // BUG-311: the API sends csv/xlsx. This used to mock 'Excel' — a value the wire has never
    // carried — so the spec was green by agreeing with a wrong type instead of with the API.
    availableExportFormats: ['csv', 'xlsx'],
  };
}

const cycles: ICompletedCycleOption[] = [
  { cycleId: 'c-1', cycleName: '2026 Annual', ratingsPublishedOn: '2026-05-01' },
];

describe('RecommendationWorkspaceComponent (US-PRF-010)', () => {
  let fixture: ComponentFixture<RecommendationWorkspaceComponent>;
  let component: RecommendationWorkspaceComponent;
  let serviceSpy: jasmine.SpyObj<RecommendationService>;
  let toastrSpy: jasmine.SpyObj<ToastrService>;

  async function setup(
    ws: IRecommendationWorkspace,
    cycleList = cycles,
  ): Promise<void> {
    serviceSpy = jasmine.createSpyObj<RecommendationService>(
      'RecommendationService',
      [
        'getCompletedCycles',
        'getWorkspace',
        'autoGenerate',
        'updateRecommendation',
        'submit',
        'export',
      ],
    );
    serviceSpy.getCompletedCycles.and.returnValue(of(cycleList));
    serviceSpy.getWorkspace.and.returnValue(of(ws));
    serviceSpy.autoGenerate.and.returnValue(
      of({ applied: true, rows: [], affectedCount: 0 }),
    );
    serviceSpy.updateRecommendation.and.returnValue(of(ws.page.rows[0]));
    serviceSpy.submit.and.returnValue(
      of({ ...ws.page.rows[0], status: 'Submitted' }),
    );

    toastrSpy = jasmine.createSpyObj<ToastrService>('ToastrService', [
      'success',
      'error',
    ]);

    await TestBed.configureTestingModule({
      imports: [RecommendationWorkspaceComponent],
      providers: [
        provideRouter([]),
        provideNoopAnimations(),
        { provide: RecommendationService, useValue: serviceSpy },
        { provide: ToastrService, useValue: toastrSpy },
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(RecommendationWorkspaceComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  }

  it('loads cycles then the workspace for the first cycle (AC-1)', async () => {
    await setup(workspace([row()]));
    expect(component.cycleId()).toBe('c-1');
    expect(serviceSpy.getWorkspace).toHaveBeenCalled();
    expect(component.rows().length).toBe(1);
  });

  it('renders the sensitive-data banner (NFR-5/§8)', async () => {
    await setup(workspace([row()]));
    const el = fixture.nativeElement as HTMLElement;
    expect(el.querySelector('[data-testid="sensitive-banner"]')).toBeTruthy();
  });

  it('renders a status chip per row (AC-3)', async () => {
    await setup(workspace([row({ status: 'Approved' })]));
    const chip = (fixture.nativeElement as HTMLElement).querySelector(
      '[data-testid="status-chip"]',
    );
    expect(chip?.textContent).toContain('Approved');
  });

  it('only shows export buttons for backend-reported formats (FR-6)', async () => {
    // BUG-311: this used to assert on 'Excel'/'Pdf' — values the API has NEVER sent. It passed because
    // it agreed with a wrong union, not because the component was right, and it would have stayed green
    // if the export buttons had stopped rendering entirely. It now asserts the real wire tokens.
    const ws = workspace([row()]);
    ws.availableExportFormats = ['csv']; // the backend reports ONE format for this run
    await setup(ws);

    const el = fixture.nativeElement as HTMLElement;
    expect(el.querySelector('[data-testid="export-csv"]'))
      .withContext('the reported format must render a button')
      .toBeTruthy();
    expect(el.querySelector('[data-testid="export-xlsx"]'))
      .withContext('a format the backend did NOT report must not render — that is what FR-6 claims')
      .toBeFalsy();
  });

  it('labels export buttons with display copy, not raw wire tokens (BUG-311)', async () => {
    const ws = workspace([row()]);
    ws.availableExportFormats = ['xlsx'];
    await setup(ws);

    const btn = (fixture.nativeElement as HTMLElement).querySelector('[data-testid="export-xlsx"]');
    expect(btn?.textContent?.trim())
      .withContext('"Export xlsx" is a wire token leaking into user-facing copy')
      .toBe('Export Excel (XLSX)');
  });

  // ── budget tracker thresholds (FR-8/BR-4) ──
  it('renders an amber/warning bar at 80% consumption', async () => {
    await setup(workspace([row()], { allocated: 100000, consumed: 80000 }));
    expect(component.budgetBarClass()).toContain('amber');
    expect(component.budgetExceeded()).toBeFalse();
  });

  it('renders a green/healthy bar below 80%', async () => {
    await setup(workspace([row()], { allocated: 100000, consumed: 20000 }));
    expect(component.budgetBarClass()).toContain('emerald');
  });

  it('shows the soft exceeded warning above 100% (BR-4)', async () => {
    await setup(workspace([row()], { allocated: 100000, consumed: 120000 }));
    fixture.detectChanges();
    expect(component.budgetExceeded()).toBeTrue();
    expect(component.budgetBarClass()).toContain('rose');
    const warn = (fixture.nativeElement as HTMLElement).querySelector(
      '[data-testid="budget-warning"]',
    );
    expect(warn).toBeTruthy();
    // bar width is clamped to 100 even though consumption is 120%
    expect(component.budgetBarWidth()).toBe(100);
  });

  // ── auto-gen wizard preview (AC-2/FR-2) ──
  it('builds a rule PREVIEW from page rows without persisting (BR-3)', async () => {
    await setup(
      workspace([
        row({ recommendationId: 'a', employeeId: 'a', finalScore: 4.8 }),
        row({ recommendationId: 'b', employeeId: 'b', finalScore: 3.0 }),
      ]),
    );
    component.openWizard();
    component.wizardRules.set([
      { minScore: 4.5, type: 'Promotion', amount: null, percentage: null },
    ]);
    component.previewWizard();

    expect(component.wizardStep()).toBe(2);
    expect(component.previewRows().length).toBe(2);
    expect(component.previewRows()[0].proposedType).toBe('Promotion');
    expect(component.previewRows()[1].proposedType).toBe('None');
    expect(component.previewAffected()).toBe(1);
    // preview must NOT have hit the persist endpoint
    expect(serviceSpy.autoGenerate).not.toHaveBeenCalled();
  });

  it('apply persists with preview=false (AC-2)', async () => {
    await setup(workspace([row({ finalScore: 4.8 })]));
    component.openWizard();
    component.previewWizard();
    component.applyWizard();
    expect(serviceSpy.autoGenerate).toHaveBeenCalledWith(
      jasmine.any(Object),
      false,
    );
    expect(toastrSpy.success).toHaveBeenCalled();
  });

  // ── inline edit / override justification gate (FR-3) ──
  it('blocks saving a manual recommendation without a justification (FR-3)', async () => {
    await setup(workspace([row({ autoGenerated: false })]));
    component.openEdit(component.rows()[0]);
    component.form.type = 'Bonus';
    component.form.justification = '';
    expect(component.justificationRequired()).toBeTrue();
    expect(component.canSaveEdit()).toBeFalse();

    component.saveEdit(component.rows()[0]);
    expect(serviceSpy.updateRecommendation).not.toHaveBeenCalled();
    expect(toastrSpy.error).toHaveBeenCalled();
  });

  it('allows saving an override once a justification is provided (FR-3)', async () => {
    await setup(workspace([row({ autoGenerated: true })]));
    component.openEdit(component.rows()[0]);
    component.form.type = 'Promotion';
    component.form.justification = 'Consistently exceeds expectations';
    expect(component.canSaveEdit()).toBeTrue();

    component.saveEdit(component.rows()[0]);
    expect(serviceSpy.updateRecommendation).toHaveBeenCalled();
    expect(toastrSpy.success).toHaveBeenCalled();
  });

  // ── submit (AC-3) ──
  it('submits a draft recommendation into the workflow (AC-3)', async () => {
    await setup(workspace([row({ status: 'Draft' })]));
    component.submit(component.rows()[0]);
    expect(serviceSpy.submit).toHaveBeenCalledWith('r-1');
    expect(toastrSpy.success).toHaveBeenCalled();
  });

  it('shows an error state with retry when the workspace fails to load', async () => {
    serviceSpy = jasmine.createSpyObj<RecommendationService>(
      'RecommendationService',
      ['getCompletedCycles', 'getWorkspace'],
    );
    serviceSpy.getCompletedCycles.and.returnValue(of(cycles));
    serviceSpy.getWorkspace.and.returnValue(throwError(() => new Error('x')));
    toastrSpy = jasmine.createSpyObj<ToastrService>('ToastrService', [
      'success',
      'error',
    ]);

    await TestBed.configureTestingModule({
      imports: [RecommendationWorkspaceComponent],
      providers: [
        provideRouter([]),
        provideNoopAnimations(),
        { provide: RecommendationService, useValue: serviceSpy },
        { provide: ToastrService, useValue: toastrSpy },
      ],
    }).compileComponents();
    fixture = TestBed.createComponent(RecommendationWorkspaceComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();

    expect(component.error()).toBeTruthy();
    expect(component.loading()).toBeFalse();
  });
});
