import {
  BUDGET_HEALTH_BAR,
  IAutoGenerateRule,
  IBudgetTracker,
  ICycleComparisonStat,
  IRecommendationRow,
  IUpdateRecommendationRequest,
  RECOMMENDATION_STATUS_BADGE,
  RECOMMENDATION_STATUS_LABEL,
  RecommendationStatus,
  budgetConsumedPercent,
  budgetHealth,
  budgetRemaining,
  buildAutoPreview,
  comparisonDelta,
  deptBarPercent,
  formatTenure,
  isOverrideJustified,
  matchAutoRule,
} from './recommendation.models';

describe('recommendation.models helpers (US-PRF-010)', () => {
  // ── AC-2/FR-2: auto-gen rule preview ──
  describe('matchAutoRule', () => {
    const rules: IAutoGenerateRule[] = [
      { minScore: 4.5, type: 'Promotion', amount: null, percentage: null },
      { minScore: 3.5, type: 'Bonus', amount: 1000, percentage: null },
    ];

    it('picks the STRONGEST matching rule (highest threshold wins)', () => {
      expect(matchAutoRule(4.8, rules)?.type).toBe('Promotion');
    });

    it('falls to the lower threshold when the top is not met', () => {
      const m = matchAutoRule(3.6, rules);
      expect(m?.type).toBe('Bonus');
      expect(m?.amount).toBe(1000);
    });

    it('returns null below every threshold', () => {
      expect(matchAutoRule(2.0, rules)).toBeNull();
    });

    it('returns null for an unrated (null) score', () => {
      expect(matchAutoRule(null, rules)).toBeNull();
    });

    it('is order-independent (sorts internally)', () => {
      const reversed = [...rules].reverse();
      expect(matchAutoRule(4.9, reversed)?.type).toBe('Promotion');
    });
  });

  describe('buildAutoPreview', () => {
    const rules: IAutoGenerateRule[] = [
      { minScore: 4.5, type: 'Promotion', amount: null, percentage: null },
      { minScore: 3.5, type: 'Bonus', amount: 500, percentage: null },
    ];

    function row(
      id: string,
      score: number | null,
      autoGenerated = true,
      type: IRecommendationRow['detail']['type'] = 'None',
    ): IRecommendationRow {
      return {
        recommendationId: id,
        employeeId: id,
        employeeName: `Emp ${id}`,
        employeeNo: `E${id}`,
        departmentId: 'd1',
        departmentName: 'Eng',
        jobTitle: 'Dev',
        finalScore: score,
        scoreScaleMax: 5,
        currentGrade: 'G3',
        currentCompensation: 60000,
        tenureMonths: 24,
        managerFlag: null,
        status: 'Draft',
        autoGenerated,
        detail: {
          type,
          amount: null,
          percentage: null,
          targetGrade: null,
          targetTitle: null,
          effectiveDate: null,
          trainingCourse: null,
          justification: null,
        },
      };
    }

    it('proposes a type per employee and counts only non-None', () => {
      const preview = buildAutoPreview(
        [row('1', 4.8), row('2', 3.6), row('3', 2.0)],
        rules,
        false,
      );
      expect(preview.applied).toBe(false);
      expect(preview.rows.map((r) => r.proposedType)).toEqual([
        'Promotion',
        'Bonus',
        'None',
      ]);
      expect(preview.affectedCount).toBe(2);
      expect(preview.rows[1].amount).toBe(500);
    });

    it('skips rows with an existing MANUAL recommendation when requested (BR-3)', () => {
      const manual = row('9', 4.9, false, 'Bonus'); // manual, non-None
      const preview = buildAutoPreview([manual, row('1', 4.8)], rules, true);
      expect(preview.rows.length).toBe(1);
      expect(preview.rows[0].employeeId).toBe('1');
    });

    it('does NOT skip a manual row when skipManualOverrides is false', () => {
      const manual = row('9', 4.9, false, 'Bonus');
      const preview = buildAutoPreview([manual, row('1', 4.8)], rules, false);
      expect(preview.rows.length).toBe(2);
    });
  });

  // ── FR-3: manual-override justification gate ──
  describe('isOverrideJustified', () => {
    function req(
      type: IUpdateRecommendationRequest['type'],
      justification: string | null,
    ): IUpdateRecommendationRequest {
      return {
        type,
        amount: null,
        percentage: null,
        targetGrade: null,
        targetTitle: null,
        effectiveDate: null,
        trainingCourse: null,
        justification,
      };
    }

    it('blocks a non-None recommendation without a justification', () => {
      expect(isOverrideJustified(req('Bonus', null), false)).toBe(false);
      expect(isOverrideJustified(req('Bonus', '   '), false)).toBe(false);
    });

    it('allows a non-None recommendation WITH a justification', () => {
      expect(isOverrideJustified(req('Bonus', 'High performer'), false)).toBe(
        true,
      );
    });

    it('requires a justification when overriding an AUTO-generated row', () => {
      // type None but was auto-generated → clearing is fine (None short-circuits)
      expect(isOverrideJustified(req('None', null), true)).toBe(true);
      // changing it to Promotion (auto-generated) needs justification
      expect(isOverrideJustified(req('Promotion', null), true)).toBe(false);
      expect(isOverrideJustified(req('Promotion', 'ready'), true)).toBe(true);
    });

    it('never requires a justification to CLEAR a recommendation (type None)', () => {
      expect(isOverrideJustified(req('None', null), false)).toBe(true);
      expect(isOverrideJustified(req('None', null), true)).toBe(true);
    });
  });

  // ── FR-8/BR-4: budget tracker thresholds + colors ──
  describe('budget tracker', () => {
    function b(
      allocated: number,
      consumed: number,
      enabled = true,
    ): IBudgetTracker {
      return { enabled, currency: 'USD', allocated, consumed };
    }

    it('budgetConsumedPercent rounds the consumed ratio', () => {
      expect(budgetConsumedPercent(b(100000, 50000))).toBe(50);
      expect(budgetConsumedPercent(b(100000, 0))).toBe(0);
    });

    it('budgetConsumedPercent is 0 when disabled or zero allocation', () => {
      expect(budgetConsumedPercent(b(100000, 50000, false))).toBe(0);
      expect(budgetConsumedPercent(b(0, 50000))).toBe(0);
    });

    it('budgetRemaining can go negative when exceeded', () => {
      expect(budgetRemaining(b(100000, 110000))).toBe(-10000);
    });

    it('budgetHealth is Healthy below 80%', () => {
      expect(budgetHealth(b(100000, 50000))).toBe('Healthy');
      expect(budgetHealth(b(100000, 79999))).toBe('Healthy');
    });

    it('budgetHealth is Warning between 80% and 100%', () => {
      expect(budgetHealth(b(100000, 80000))).toBe('Warning');
      expect(budgetHealth(b(100000, 100000))).toBe('Warning');
    });

    it('budgetHealth is Exceeded above 100% (soft warning, BR-4)', () => {
      expect(budgetHealth(b(100000, 110000))).toBe('Exceeded');
    });

    it('maps each health band to a distinct bar color', () => {
      expect(BUDGET_HEALTH_BAR.Healthy).toContain('emerald');
      expect(BUDGET_HEALTH_BAR.Warning).toContain('amber');
      expect(BUDGET_HEALTH_BAR.Exceeded).toContain('rose');
    });
  });

  // ── status chip mapping (AC-3/AC-5) ──
  describe('status chip mapping', () => {
    const statuses: RecommendationStatus[] = [
      'Draft',
      'Submitted',
      'PendingApproval',
      'Approved',
      'Rejected',
    ];

    it('has a badge + label for every status', () => {
      for (const s of statuses) {
        expect(RECOMMENDATION_STATUS_BADGE[s]).toBeTruthy();
        expect(RECOMMENDATION_STATUS_LABEL[s]).toBeTruthy();
      }
    });

    it('uses recognizable color cues per status', () => {
      expect(RECOMMENDATION_STATUS_BADGE.Approved).toContain('emerald');
      expect(RECOMMENDATION_STATUS_BADGE.Rejected).toContain('rose');
      expect(RECOMMENDATION_STATUS_BADGE.PendingApproval).toContain('amber');
    });
  });

  // ── summary helpers (AC-4) ──
  describe('summary helpers', () => {
    it('deptBarPercent scales against the peak with a 2% floor', () => {
      expect(deptBarPercent(50, 100)).toBe(50);
      expect(deptBarPercent(0, 100)).toBe(2);
      expect(deptBarPercent(10, 0)).toBe(0);
    });

    it('comparisonDelta is current minus previous', () => {
      const stat: ICycleComparisonStat = {
        label: 'Promotions',
        current: 12,
        previous: 8,
      };
      expect(comparisonDelta(stat)).toBe(4);
    });
  });

  describe('formatTenure', () => {
    it('formats months into y/m', () => {
      expect(formatTenure(0)).toBe('0m');
      expect(formatTenure(5)).toBe('5m');
      expect(formatTenure(12)).toBe('1y');
      expect(formatTenure(30)).toBe('2y 6m');
    });

    it('renders a dash for null/negative', () => {
      expect(formatTenure(null)).toBe('—');
      expect(formatTenure(-3)).toBe('—');
    });
  });
});
