namespace HRM.Domain.Enums;

/// <summary>
/// Lifecycle status of a leave request (US-LV-003 §7).
/// Stored as a string in the database to match the leave enum convention.
/// US-LV-003 only ever creates requests in the Pending state; the remaining
/// states are populated by the approval/cancellation flows (US-LV-004/005).
/// </summary>
public enum LeaveRequestStatus
{
    Pending = 0,
    Approved = 1,
    Rejected = 2,
    Cancelled = 3,

    /// <summary>
    /// LOP entry auto-generated by the absenteeism reconciliation job (US-LV-011 FR-4, AC-2).
    /// Created with is_lop = true and lop_source = SystemGenerated. No approval flow — it is a
    /// system record of an unaccounted absence. May be overridden by HR (BR-3).
    /// </summary>
    SystemGenerated = 4,

    /// <summary>
    /// LOP entry manually assigned by HR (US-LV-011 FR-4, AC-3). Created with is_lop = true and
    /// lop_source = HrAssigned. Treated as a finalised LOP record (no pending approval).
    /// </summary>
    HrAssigned = 5,
}
