import { TestBed } from '@angular/core/testing';
import {
  HttpTestingController,
  provideHttpClientTesting,
} from '@angular/common/http/testing';
import { HttpResponse, provideHttpClient } from '@angular/common/http';

import { RecommendationService } from './recommendation.service';
import { environment } from '../../../../environments/environment';
import {
  IAutoGenerateRequest,
  ICompletedCycleOption,
  IRecommendationRow,
  IRecommendationWorkspace,
  IUpdateRecommendationRequest,
  RecommendationWorkspaceRowWire,
  RecommendationWorkspaceWire,
} from '../models/recommendation.models';

describe('RecommendationService (US-PRF-010)', () => {
  let service: RecommendationService;
  let httpMock: HttpTestingController;
  const baseUrl = `${environment.apiBaseUrl}/tenant/performance/recommendations`;

  const cycle: ICompletedCycleOption = {
    cycleId: 'c-1',
    cycleName: '2026 Annual',
    ratingsPublishedOn: '2026-05-01',
  };

  // The view-model the mapper is expected to PRODUCE (what components consume).
  const row: IRecommendationRow = {
    recommendationId: 'r-1',
    employeeId: 'e-1',
    employeeName: 'Alex Doe',
    employeeNo: 'E1',
    departmentId: 'd-1',
    departmentName: 'Eng',
    jobTitle: 'Engineer',
    finalScore: 4.6,
    scoreScaleMax: 5,
    currentGrade: 'G3',
    currentCompensation: 60000,
    tenureMonths: 30,
    managerFlag: 'Promotion',
    status: 'Draft',
    autoGenerated: true,
    detail: {
      type: 'Promotion',
      amount: null,
      percentage: null,
      targetGrade: 'G4',
      targetTitle: null,
      effectiveDate: '2026-07-01',
      trainingCourse: null,
      justification: null,
    },
  };

  // The REAL wire row (PerformanceRecommendationWorkspaceRowDto): the editable detail
  // is nested under `recommendation`, the title is `currentTitle`, and there is NO
  // per-row scale — `scoreScaleMax` comes from the workspace `ratingScaleMax`. Mapping
  // this must reproduce `row` exactly.
  const wireRow: RecommendationWorkspaceRowWire = {
    employeeId: 'e-1',
    employeeName: 'Alex Doe',
    employeeNo: 'E1',
    departmentId: 'd-1',
    departmentName: 'Eng',
    currentTitle: 'Engineer',
    currentGrade: 'G3',
    currentCompensation: 60000,
    tenureMonths: 30,
    finalScore: 4.6,
    managerFlagName: 'Promotion',
    recommendation: {
      id: 'r-1',
      statusName: 'Draft',
      isAutoGenerated: true,
      typeName: 'Promotion',
      bonusAmount: null,
      bonusPercent: null,
      incrementAmount: null,
      incrementPercent: null,
      targetGrade: 'G4',
      targetTitle: null,
      effectiveDate: '2026-07-01',
      trainingCourse: null,
      justification: null,
    },
  };

  /**
   * The REAL workspace wire (PerformanceRecommendationWorkspaceDto): FLAT — `rows`,
   * `totalCount`, `page` (the page NUMBER), and `pageSize` are siblings, NOT a nested
   * `page` object, and the scale is workspace-level `ratingScaleMax`. This is the shape
   * the un-migrated `ws.page.rows` cast silently mis-read as an empty list.
   */
  const wireWorkspace = (
    over: Partial<RecommendationWorkspaceWire> = {},
  ): RecommendationWorkspaceWire => ({
    cycleId: 'c-1',
    cycleName: '2026 Annual',
    ratingScaleMax: 5,
    rows: [wireRow],
    totalCount: 1,
    page: 1,
    pageSize: 25,
    budget: { allocatedAmount: 100000, consumedAmount: 0, currency: 'USD' },
    compensationVisible: true,
    availableExportFormats: ['Excel'],
    ...over,
  });

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [
        RecommendationService,
        provideHttpClient(),
        provideHttpClientTesting(),
      ],
    });
    service = TestBed.inject(RecommendationService);
    httpMock = TestBed.inject(HttpTestingController);
  });

  afterEach(() => httpMock.verify());

  it('getCompletedCycles() GETs cycles with credentials (bare array)', () => {
    let result: ICompletedCycleOption[] | undefined;
    service.getCompletedCycles().subscribe((r) => (result = r));

    const req = httpMock.expectOne(`${baseUrl}/cycles/completed`);
    expect(req.request.method).toBe('GET');
    expect(req.request.withCredentials).toBeTrue();
    req.flush([cycle]);

    expect(result).toEqual([cycle]);
  });

  it('getCompletedCycles() unwraps a { data } page', () => {
    let result: ICompletedCycleOption[] | undefined;
    service.getCompletedCycles().subscribe((r) => (result = r));

    const req = httpMock.expectOne(`${baseUrl}/cycles/completed`);
    req.flush({ data: [cycle] });

    expect(result).toEqual([cycle]);
  });

  it('getWorkspace() passes params and re-nests the FLAT wire rows/page into the view-model', () => {
    let result: IRecommendationWorkspace | undefined;
    service
      .getWorkspace('c-1', {
        sort: 'score',
        dir: 'desc',
        page: 2,
        pageSize: 20,
      })
      .subscribe((r) => (result = r));

    const req = httpMock.expectOne(
      (r) => r.url === `${baseUrl}/workspace`,
    );
    expect(req.request.method).toBe('GET');
    expect(req.request.params.get('cycleId')).toBe('c-1');
    expect(req.request.params.get('sort')).toBe('score');
    expect(req.request.params.get('dir')).toBe('desc');
    expect(req.request.params.get('page')).toBe('2');
    expect(req.request.params.get('pageSize')).toBe('20');
    // Flat wire: page is the NUMBER 2, rows/totalCount are top-level siblings.
    req.flush(wireWorkspace({ page: 2, pageSize: 20 }));

    // The un-migrated `ws.page.rows` read `undefined` here (page is a number); the
    // mapper must surface the real row the API sent, and re-nest paging.
    expect(result?.page.rows).toEqual([row]);
    expect(result?.page.totalCount).toBe(1);
    expect(result?.page.page).toBe(2);
    expect(result?.budget.enabled).toBeTrue();
    expect(result?.budget.allocated).toBe(100000);
    expect(result?.compensationVisible).toBeTrue();
  });

  it('autoGenerate() defaults to preview=true', () => {
    const body: IAutoGenerateRequest = {
      cycleId: 'c-1',
      rules: [
        { minScore: 4.5, type: 'Promotion', amount: null, percentage: null },
      ],
      skipManualOverrides: true,
    };
    service.autoGenerate(body).subscribe();

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/auto-generate`);
    expect(req.request.method).toBe('POST');
    expect(req.request.params.get('preview')).toBe('true');
    expect(req.request.body).toEqual(body);
    req.flush({ applied: false, rows: [], affectedCount: 0 });
  });

  it('autoGenerate(preview=false) persists', () => {
    const body: IAutoGenerateRequest = {
      cycleId: 'c-1',
      rules: [],
      skipManualOverrides: false,
    };
    service.autoGenerate(body, false).subscribe();

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/auto-generate`);
    expect(req.request.params.get('preview')).toBe('false');
    req.flush({ applied: true, rows: [], affectedCount: 0 });
  });

  it('updateRecommendation() POSTs the Save upsert body keyed by employee + cycle', () => {
    const form: IUpdateRecommendationRequest = {
      type: 'Bonus',
      amount: 5000,
      percentage: null,
      targetGrade: null,
      targetTitle: null,
      effectiveDate: null,
      trainingCourse: null,
      justification: 'High impact this cycle',
    };
    service.updateRecommendation('e-1', 'c-1', form).subscribe();

    const req = httpMock.expectOne(`${baseUrl}`);
    expect(req.request.method).toBe('POST');
    expect(req.request.withCredentials).toBeTrue();
    expect(req.request.body).toEqual({
      employeeId: 'e-1',
      cycleId: 'c-1',
      type: 'Bonus',
      details: {
        targetGrade: null,
        targetTitle: null,
        effectiveDate: null,
        bonusAmount: 5000,
        bonusPercent: null,
        incrementAmount: null,
        incrementPercent: null,
        trainingCourse: null,
        customTypeLabel: null,
        budgetId: null,
      },
      justification: 'High impact this cycle',
    });
    req.flush(row);
  });

  it('submit() POSTs to the submit route with an optional comment', () => {
    service.submit('r-1', 'finalized').subscribe();

    const req = httpMock.expectOne(`${baseUrl}/r-1/submit`);
    expect(req.request.method).toBe('POST');
    expect(req.request.body).toEqual({ comment: 'finalized' });
    req.flush({ ...row, status: 'Submitted' });
  });

  it('submit() sends null comment when omitted', () => {
    service.submit('r-1').subscribe();

    const req = httpMock.expectOne(`${baseUrl}/r-1/submit`);
    expect(req.request.body).toEqual({ comment: null });
    req.flush(row);
  });

  it('decide() POSTs to the approve route with the comment body', () => {
    service.decide('r-1', 'Approve', 'looks good').subscribe();

    const req = httpMock.expectOne(`${baseUrl}/r-1/approve`);
    expect(req.request.method).toBe('POST');
    expect(req.request.body).toEqual({ comment: 'looks good' });
    req.flush({ ...row, status: 'Approved' });
  });

  it('decide() POSTs to the reject route when rejecting', () => {
    service.decide('r-1', 'Reject').subscribe();

    const req = httpMock.expectOne(`${baseUrl}/r-1/reject`);
    expect(req.request.method).toBe('POST');
    expect(req.request.body).toEqual({ comment: null });
    req.flush({ ...row, status: 'Rejected' });
  });

  it('getBudget() GETs the budget for a cycle', () => {
    service.getBudget('c-1').subscribe();

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/budget`);
    expect(req.request.params.get('cycleId')).toBe('c-1');
    req.flush({ enabled: true, currency: 'USD', allocated: 1, consumed: 0 });
  });

  it('getSummary() GETs the aggregate summary', () => {
    service.getSummary('c-1').subscribe();

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/summary`);
    expect(req.request.method).toBe('GET');
    expect(req.request.params.get('cycleId')).toBe('c-1');
    req.flush({
      cycleId: 'c-1',
      cycleName: '2026 Annual',
      currency: 'USD',
      totalPromotions: 3,
      totalBonuses: 5,
      totalIncrements: 4,
      totalTrainingNominations: 2,
      bonusPoolAllocated: 50000,
      byDepartment: [],
      comparison: [],
    });
  });

  // ── ARM (Break 1): the manager team list must surface the rows the API ACTUALLY
  //    sent. Against the un-migrated `ws.page.rows` read this returns [] (page is a
  //    number), so this assertion fails until the mapper lands.
  it('getTeamRecommendations() surfaces the rows the wire sent as a flat sibling of the page number', () => {
    let result: IRecommendationRow[] | undefined;
    service.getTeamRecommendations('c-1').subscribe((r) => (result = r));

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/workspace`);
    expect(req.request.method).toBe('GET');
    expect(req.request.params.get('cycleId')).toBe('c-1');
    req.flush(wireWorkspace());

    expect(result).toEqual([row]);
  });

  it('getTeamRecommendations() returns [] when the workspace sent no rows', () => {
    let result: IRecommendationRow[] | undefined;
    service.getTeamRecommendations('c-1').subscribe((r) => (result = r));

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/workspace`);
    req.flush(wireWorkspace({ rows: [], totalCount: 0 }));

    expect(result).toEqual([]);
  });

  it('export() requests a blob with format + cycle params', () => {
    let response: HttpResponse<Blob> | undefined;
    service.export('Excel', 'c-1').subscribe((r) => (response = r));

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/summary/export`);
    expect(req.request.method).toBe('GET');
    expect(req.request.params.get('format')).toBe('Excel');
    expect(req.request.params.get('cycleId')).toBe('c-1');
    expect(req.request.responseType).toBe('blob');

    const blob = new Blob(['x'], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
    req.flush(blob, {
      headers: { 'Content-Disposition': 'attachment; filename="recs.xlsx"' },
    });

    expect(response?.body).toBeInstanceOf(Blob);
    expect(response?.headers.get('Content-Disposition')).toContain('recs.xlsx');
  });
});
