import { TestBed } from '@angular/core/testing';
import {
  HttpTestingController,
  provideHttpClientTesting,
} from '@angular/common/http/testing';
import { HttpResponse, provideHttpClient } from '@angular/common/http';

import { RecommendationService } from './recommendation.service';
import { environment } from '../../../../environments/environment';
import {
  IAutoGenerateRequest,
  ICompletedCycleOption,
  IRecommendationRow,
  IUpdateRecommendationRequest,
} from '../models/recommendation.models';

describe('RecommendationService (US-PRF-010)', () => {
  let service: RecommendationService;
  let httpMock: HttpTestingController;
  const baseUrl = `${environment.apiBaseUrl}/tenant/performance/recommendations`;

  const cycle: ICompletedCycleOption = {
    cycleId: 'c-1',
    cycleName: '2026 Annual',
    ratingsPublishedOn: '2026-05-01',
  };

  const row: IRecommendationRow = {
    recommendationId: 'r-1',
    employeeId: 'e-1',
    employeeName: 'Alex Doe',
    employeeNo: 'E1',
    departmentId: 'd-1',
    departmentName: 'Eng',
    jobTitle: 'Engineer',
    finalScore: 4.6,
    scoreScaleMax: 5,
    currentGrade: 'G3',
    currentCompensation: 60000,
    tenureMonths: 30,
    managerFlag: 'PromotionConsideration',
    status: 'Draft',
    autoGenerated: true,
    detail: {
      type: 'Promotion',
      amount: null,
      percentage: null,
      targetGrade: 'G4',
      targetTitle: null,
      effectiveDate: '2026-07-01',
      trainingCourse: null,
      justification: null,
    },
  };

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [
        RecommendationService,
        provideHttpClient(),
        provideHttpClientTesting(),
      ],
    });
    service = TestBed.inject(RecommendationService);
    httpMock = TestBed.inject(HttpTestingController);
  });

  afterEach(() => httpMock.verify());

  it('getCompletedCycles() GETs cycles with credentials (bare array)', () => {
    let result: ICompletedCycleOption[] | undefined;
    service.getCompletedCycles().subscribe((r) => (result = r));

    const req = httpMock.expectOne(`${baseUrl}/cycles/completed`);
    expect(req.request.method).toBe('GET');
    expect(req.request.withCredentials).toBeTrue();
    req.flush([cycle]);

    expect(result).toEqual([cycle]);
  });

  it('getCompletedCycles() unwraps a { data } page', () => {
    let result: ICompletedCycleOption[] | undefined;
    service.getCompletedCycles().subscribe((r) => (result = r));

    const req = httpMock.expectOne(`${baseUrl}/cycles/completed`);
    req.flush({ data: [cycle] });

    expect(result).toEqual([cycle]);
  });

  it('getWorkspace() passes cycle + sort + paging query params', () => {
    service
      .getWorkspace('c-1', {
        sort: 'score',
        dir: 'desc',
        page: 2,
        pageSize: 20,
      })
      .subscribe();

    const req = httpMock.expectOne(
      (r) => r.url === `${baseUrl}/workspace`,
    );
    expect(req.request.method).toBe('GET');
    expect(req.request.params.get('cycleId')).toBe('c-1');
    expect(req.request.params.get('sort')).toBe('score');
    expect(req.request.params.get('dir')).toBe('desc');
    expect(req.request.params.get('page')).toBe('2');
    expect(req.request.params.get('pageSize')).toBe('20');
    req.flush({
      cycleId: 'c-1',
      cycleName: '2026 Annual',
      page: { rows: [row], totalCount: 1, page: 2, pageSize: 20 },
      budget: { enabled: true, currency: 'USD', allocated: 100000, consumed: 0 },
      compensationVisible: true,
      availableExportFormats: ['Excel'],
    });
  });

  it('autoGenerate() defaults to preview=true', () => {
    const body: IAutoGenerateRequest = {
      cycleId: 'c-1',
      rules: [
        { minScore: 4.5, type: 'Promotion', amount: null, percentage: null },
      ],
      skipManualOverrides: true,
    };
    service.autoGenerate(body).subscribe();

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/auto-generate`);
    expect(req.request.method).toBe('POST');
    expect(req.request.params.get('preview')).toBe('true');
    expect(req.request.body).toEqual(body);
    req.flush({ applied: false, rows: [], affectedCount: 0 });
  });

  it('autoGenerate(preview=false) persists', () => {
    const body: IAutoGenerateRequest = {
      cycleId: 'c-1',
      rules: [],
      skipManualOverrides: false,
    };
    service.autoGenerate(body, false).subscribe();

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/auto-generate`);
    expect(req.request.params.get('preview')).toBe('false');
    req.flush({ applied: true, rows: [], affectedCount: 0 });
  });

  it('updateRecommendation() PUTs the override body', () => {
    const body: IUpdateRecommendationRequest = {
      type: 'Bonus',
      amount: 5000,
      percentage: null,
      targetGrade: null,
      targetTitle: null,
      effectiveDate: null,
      trainingCourse: null,
      justification: 'High impact this cycle',
    };
    service.updateRecommendation('r-1', body).subscribe();

    const req = httpMock.expectOne(`${baseUrl}/r-1`);
    expect(req.request.method).toBe('PUT');
    expect(req.request.body).toEqual(body);
    expect(req.request.withCredentials).toBeTrue();
    req.flush(row);
  });

  it('submit() POSTs to the submit route with an optional comment', () => {
    service.submit('r-1', 'finalized').subscribe();

    const req = httpMock.expectOne(`${baseUrl}/r-1/submit`);
    expect(req.request.method).toBe('POST');
    expect(req.request.body).toEqual({ comment: 'finalized' });
    req.flush({ ...row, status: 'Submitted' });
  });

  it('submit() sends null comment when omitted', () => {
    service.submit('r-1').subscribe();

    const req = httpMock.expectOne(`${baseUrl}/r-1/submit`);
    expect(req.request.body).toEqual({ comment: null });
    req.flush(row);
  });

  it('decide() POSTs the approver decision', () => {
    service.decide('r-1', 'Approve', 'looks good').subscribe();

    const req = httpMock.expectOne(`${baseUrl}/r-1/decision`);
    expect(req.request.method).toBe('POST');
    expect(req.request.body).toEqual({
      decision: 'Approve',
      comment: 'looks good',
    });
    req.flush({ ...row, status: 'Approved' });
  });

  it('getBudget() GETs the budget for a cycle', () => {
    service.getBudget('c-1').subscribe();

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/budget`);
    expect(req.request.params.get('cycleId')).toBe('c-1');
    req.flush({ enabled: true, currency: 'USD', allocated: 1, consumed: 0 });
  });

  it('getSummary() GETs the aggregate summary', () => {
    service.getSummary('c-1').subscribe();

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/summary`);
    expect(req.request.method).toBe('GET');
    expect(req.request.params.get('cycleId')).toBe('c-1');
    req.flush({
      cycleId: 'c-1',
      cycleName: '2026 Annual',
      currency: 'USD',
      totalPromotions: 3,
      totalBonuses: 5,
      totalIncrements: 4,
      totalTrainingNominations: 2,
      bonusPoolAllocated: 50000,
      byDepartment: [],
      comparison: [],
    });
  });

  it('getTeamRecommendations() GETs the manager team list (bare array)', () => {
    let result: IRecommendationRow[] | undefined;
    service.getTeamRecommendations('c-1').subscribe((r) => (result = r));

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/team`);
    expect(req.request.method).toBe('GET');
    expect(req.request.params.get('cycleId')).toBe('c-1');
    req.flush([row]);

    expect(result).toEqual([row]);
  });

  it('getTeamRecommendations() unwraps a { data } page', () => {
    let result: IRecommendationRow[] | undefined;
    service.getTeamRecommendations('c-1').subscribe((r) => (result = r));

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/team`);
    req.flush({ data: [] });

    expect(result).toEqual([]);
  });

  it('export() requests a blob with format + cycle params', () => {
    let response: HttpResponse<Blob> | undefined;
    service.export('Excel', 'c-1').subscribe((r) => (response = r));

    const req = httpMock.expectOne((r) => r.url === `${baseUrl}/export`);
    expect(req.request.method).toBe('GET');
    expect(req.request.params.get('format')).toBe('Excel');
    expect(req.request.params.get('cycleId')).toBe('c-1');
    expect(req.request.responseType).toBe('blob');

    const blob = new Blob(['x'], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
    req.flush(blob, {
      headers: { 'Content-Disposition': 'attachment; filename="recs.xlsx"' },
    });

    expect(response?.body).toBeInstanceOf(Blob);
    expect(response?.headers.get('Content-Disposition')).toContain('recs.xlsx');
  });
});
